# Generated by Django 5.0.3 on 2024-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='saldo_calculado',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
