# Generated by Django 5.0.3 on 2024-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
